/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClockAddress = (RCC_AHB1ENR_t*) 0x40023830; // Address of RCC (0x40023800) + offset (0x30) to be able to turn on the clock
	GPIOx_MODE_t volatile *const pModeRegisterGPIOD = (GPIOx_MODE_t*) 0x40020C00; // Use this address to configure the pin 12->15 of GPIOD that output will pass through them...
	// meaning that the LED will be able to be turned on
	GPIOx_MODE_t volatile *const pModeRegisterGPIOA = (GPIOx_MODE_t*) 0x40020000; // Use this address to configure the type of data that will pass on the inputs of GPIOA
	GPIOx_IDR_t volatile *const pModeInputGPIOA = (GPIOx_IDR_t*) 0x40020010; // Address where information that is passing through GPIO pins. Here is to read data passing
	GPIOx_ODR_t volatile *const pOutputRegisterGPIOD = (GPIOx_ODR_t*) 0x40020C14; // Address to configure the turning on/off of LEDs


	// Enable the clock for GPOID and GPOIA peripheral in the AHB1EN
	// Use the RCC to enable the clock for GPOID and GPOIA to allow of passage of voltage/information
	pClockAddress->gpiod_en = 1; // Activate clock in GPIOD to pass voltage to turn on the LEDs
	pClockAddress->gpioa_en = 1; // Activate clock in GPIOA to pass voltage to read the data from the pin

	// Configure PD12 outputs
	// Set bits 24 onwards to 01, meaning PD12->PD15 are on output mode to turn on LEDs
	pModeRegisterGPIOD->pin_12 = 1;
	pModeRegisterGPIOD->pin_13 = 1;
	pModeRegisterGPIOD->pin_14 = 1;
	pModeRegisterGPIOD->pin_15 = 1;

	// Configure PA0 as input mode
	pModeRegisterGPIOA->pin_0 = 0; // Clear the first two positions of the port a, to set those as INPUT mode

	// Turn on/of the LED
	while(1) {
		uint8_t pintStatus = pModeInputGPIOA->pin_0; // Read if the pin 0 is getting data/voltage

		if (pintStatus) {
			// Set bits 24 onwards to 1, meaning PD12->PD15 are having LEDs turned on
			pOutputRegisterGPIOD->pin_12 = 1;
			pOutputRegisterGPIOD->pin_13 = 1;
			pOutputRegisterGPIOD->pin_14 = 1;
			pOutputRegisterGPIOD->pin_15 = 1;
		} else {
			// Set bits 24 onwards to 0, meaning PD12->PD15 are having LEDs turned off
			pOutputRegisterGPIOD->pin_12 = 0;
			pOutputRegisterGPIOD->pin_13 = 0;
			pOutputRegisterGPIOD->pin_14 = 0;
			pOutputRegisterGPIOD->pin_15 = 0;
		}
	}
}
